DAPTUGWEB/Models/GioHang.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DAPTUGWEB.Models
{
    public class GioHang
    {
        public string maSP { get; set; }

        public string tenSP { get; set; }
        public double donGia { get; set; }
        public int soLuong { get; set; }
        public string anhSP { get; set; }
        public double thanhTien
        {
            get { return soLuong * donGia; }
        }

        ASP_QUAN_LY_SHOP_GIAY_6_6Entities db = new ASP_QUAN_LY_SHOP_GIAY_6_6Entities();
        public GioHang(string MaSP)
        {
            maSP = MaSP;
            SANPHAM sp = db.SANPHAMs.Single(n => n.MASP == maSP);
            tenSP = sp.TENSP;
            donGia = double.Parse(sp.DONGIA.ToString());
            soLuong = 1;
            anhSP = sp.ANHSP;

        }
    }
}

DAPTUGWEB/Models/THANHTOAN.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAPTUGWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THANHTOAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THANHTOAN()
        {
            this.HOADONs = new HashSet<HOADON>();
        }
    
        public int IDTHANHTOAN { get; set; }
        public string HTTHANHTOAN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADONs { get; set; }
    }
}

DAPTUGWEB/Controllers/GioHangController.cs
using DAPTUGWEB.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DAPTUGWEB.Controllers
{
    public class GioHangController : Controller
    {
        // GET: GioHang
        ASP_QUAN_LY_SHOP_GIAY_6_6Entities db = new ASP_QUAN_LY_SHOP_GIAY_6_6Entities();

        #region Thêm xoá sửa giỏ hàng

        public List<GioHang> LayGioHang()
        {
            List<GioHang> dssp = Session["GioHang"] as List<GioHang>;
            if (dssp == null)
            {
                dssp = new List<GioHang>();
                Session["GioHang"] = dssp;

            }
            return dssp;
        }

        // them gio hang
        public ActionResult ThemGioHang(string maSP, string url)
        {
            SANPHAM sp = db.SANPHAMs.SingleOrDefault(n => n.MASP == maSP);
            if (sp == null)
            {
                Response.StatusCode = 404;

            }
            List<GioHang> dssp = LayGioHang();
            GioHang gh = dssp.Find(n => n.maSP == maSP);
            if (gh == null)
            {
                gh = new GioHang(maSP);
                dssp.Add(gh);
                return Redirect(url);

            }
            else
            {
                gh.soLuong++;
                return Redirect(url);

            }

        }

        // cap nhat
        public ActionResult CapNhatGioHang(string maSP, FormCollection f)
        {
            SANPHAM sp = db.SANPHAMs.SingleOrDefault(n => n.MASP == maSP);
            if (sp == null)
            {
                Response.StatusCode = 404;
                return null;

            }
            List<GioHang> dssp = LayGioHang();
            GioHang gh = dssp.SingleOrDefault(n => n.maSP == maSP);
            if (gh != null)
            {
               
                gh.soLuong = int.Parse(f["textSL"].ToString());


            }
            return RedirectToAction("GioHang");
        }

        // xoa gio hang
        public ActionResult XoaGioHang(string maSP)
        {
            SANPHAM sp = db.SANPHAMs.SingleOrDefault(n => n.MASP == maSP);
            if (sp == null)
            {
                Response.StatusCode = 404;
                return null;

            }
            List<GioHang> dssp = LayGioHang();
            GioHang gh = dssp.SingleOrDefault(n => n.maSP == maSP);
            if (gh != null)
            {
                dssp.RemoveAll(n => n.maSP == gh.maSP);

            }
            if(dssp.Count == 0)
            {
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("GioHang");

        }
        public ActionResult GioHang()
        {
           
            if (Session["GioHang"] == null)
            {
                return RedirectToAction("Index", "Home");
             
            }
            List<GioHang> dssp = LayGioHang();
            ViewBag.TongTien = TongTien();

            return View(dssp);
            
        }
        private int TongSoLuong()
        {
            int TongSL = 0;
            List<GioHang> dssp = Session["GioHang"] as List<GioHang>;
            if (dssp != null)
            {

                TongSL = dssp.Sum(n => n.soLuong);
            }
            return TongSL;

        }
        private double TongTien()
        {
            double TongTien = 0;
            List<GioHang> dssp = Session["GioHang"] as List<GioHang>;
            if (dssp != null)
            {

                TongTien = dssp.Sum(n => n.thanhTien);
            }
            return TongTien;

        }

        public ActionResult GioHangPartial()
        {
            if(TongSoLuong() == 0)
            {
                return PartialView();
            }
            ViewBag.TongSoLuong = TongSoLuong();
            ViewBag.TongTien = TongTien();
            return PartialView();
        }

        public ActionResult SuaGioHang()
        {
            if (Session["GioHang"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            List<GioHang> dssp = LayGioHang();
            return View(dssp);
        }
        #endregion
        #region Đặt hàng
        public ActionResult DatHang()
        {
            if(Session["TaiKhoan"] == null || Session["TaiKhoan"].ToString() == "")
            {
                return RedirectToAction("DangNhap", "NguoiDung");
            }
            if (Session["GioHang"] == null )
            {
                return RedirectToAction("Index", "Home");
            }
            NHANVIEN nv = new NHANVIEN();
            HOADON hoadon = new HOADON();
            KHACHHANG khachhang = (KHACHHANG)Session["TaiKhoan"];
            List<GioHang> giohang = LayGioHang();
            hoadon.MAKH = khachhang.MAKH;
            hoadon.TGDAT = DateTime.Now;
            hoadon.TGGIAO = DateTime.Today.AddDays(+20);
            Random rd = new Random();
            hoadon.IDTHANHTOAN = rd.Next(0, 1);
            hoadon.DATHANHTOAN = false;
            db.HOADONs.Add(hoadon);
            db.SaveChanges();
                
            foreach (var item in giohang)
            {
                CTHD chitietHD = new CTHD();
                chitietHD.MAHD = hoadon.MAHD;
                chitietHD.MASP = item.maSP;
                chitietHD.SOLUONG = (short)item.soLuong;
                db.CTHDs.Add(chitietHD);
            }
            db.SaveChanges();
            return RedirectToAction("ThanhToan","GioHang/ThanhToan");

        }
        public ActionResult ThanhToan()
        {
            HOADON hoadon = new HOADON();
            List<GioHang> giohang = LayGioHang();
          
            hoadon.TGDAT = DateTime.Now;
            ViewBag.TgDat = hoadon.TGDAT;
            KHACHHANG khachhang = (KHACHHANG)Session["TaiKhoan"];
            ViewBag.TenKH = khachhang.TENKH;
            ViewBag.MaKH = khachhang.MAKH;
            ViewBag.SDT = khachhang.SDT;
            ViewBag.DiaChi = khachhang.DIACHI;
            ViewBag.Email = khachhang.EMAIL;
            
            ViewBag.TongTien = TongTien();
            return View();
        }
        #endregion
    }
    


}

DAPTUGWEB/Controllers/SanPhamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DAPTUGWEB.Models;

namespace DAPTUGWEB.Controllers
{
    public class SanPhamController : Controller
    {
        ASP_QUAN_LY_SHOP_GIAY_6_6Entities db = new ASP_QUAN_LY_SHOP_GIAY_6_6Entities();
        // GET: SanPham
        public PartialViewResult SanPhamPartial()
        {
            var dsSanPham = db.SANPHAMs.ToList();
            return PartialView(dsSanPham);
        }
        public ViewResult ChiTietSanPham (String MASP)
        {
            SANPHAM sp = db.SANPHAMs.SingleOrDefault(n => n.MASP == MASP);
            if(sp == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(sp);
        }

    }
}

DAPTUGWEB/Views/GioHang/GioHang.cshtml
@using DAPTUGWEB.Models;
@model List<GioHang>
@{
    ViewBag.Title = "GioHang";
    Layout = "~/Views/Layout/MainLayout.cshtml";
    var grid = new WebGrid(Model, canPage: true, defaultSort: "maSP", rowsPerPage: 3);
}

<style type="text/css">
    

    table .table1 {
        text-align: left;
        margin-left: 0px;
        margin-right: 0px;
        width: 800px;
    }

    .tr, .td {
        text-align: center;
        padding-left:40px;
    }
    #giohang {
        border-collapse: collapse;
        width:100%;
    }
        #giohang tr {
          
        }
        #giohang td {
            border: 1px solid #000;
            padding: 8px;
            text-align: center;
            align-items: center;
        }
        #giohang img {
            width: 60px;
            height: 60px;
          
        }
        #tongtien{
            margin-left:auto;
        }
        #giohang #tieude{
           background:black;
          color:white;
          font-weight:700;

        }
    .submit {
        display: block;
        position: relative;
        padding: 11px 30px;
        letter-spacing: 1px;
        background: #212121;
        font-size: 1em;
        color: #fff;
        font-weight: 600;
        border: none;
        outline: none;
        transition: 0.5s all;
        text-transform: uppercase;
    }
</style>
<div class="container">

    <table align="center" border="1" id="giohang">
        <tr id="tieude">
            <td> Ảnh sản phẩm </td>

            <td> Mã sản phẩm </td>

            <td>Tên </td>

            <td>Số lượng</td>

            <td>Đơn giá</td>

            <td>Thành tiền</td>

        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td><a href="@Url.Action("ChiTietSanPham","SanPham",new { @maSP = item.maSP})"><img src="@Url.Content("~/Image/San_pham/" + item.anhSP)" /></a></td>

                <td>@item.maSP</td>

                <td>@item.tenSP</td>

                <td>@item.soLuong</td>

                <td>@item.donGia</td>

                <td>@item.thanhTien</td>

            </tr>
        }
    </table>
    <br />
    <div class="d-flex">
        <div colspan="6" style="text-align:right">
            @*@Html.ActionLink("Chỉnh sửa giỏ hàng", "SuaGioHang")*@
            <button class="submit mr-5" onclick="location.href='@Url.Action("SuaGioHang", "GioHang")';return false;">Sửa giỏ hàng</button>
        </div>
        <br />
        <div colspan="6" style="text-align:right">
            @using (Html.BeginForm("DatHang", "GioHang"))
            {
                @*<input type="submit" value="Đặt hàng " />*@
                <button class="submit ml-5" type="submit" onclick="location.href='@Url.Action("DatHang", "GioHang")';return false;">Đặt hàng</button>
            }
        </div>
    </div>
</div>

DAPTUGWEB/Views/GioHang/GioHangPartial.cshtml
<a href="@Url.Action("GioHang","GioHang")"><i class="fa fa-shopping-cart"></i> Giỏ hàng (@ViewBag.TongSoLuong)</a>

DAPTUGWEB/Views/GioHang/SuaGioHang.cshtml
@using DAPTUGWEB.Models;
@model List<GioHang>
@{
    ViewBag.Title = "CapNhatGioHang";
    Layout = "~/Views/Layout/MainLayout.cshtml";
    var grid = new WebGrid(Model, canPage: true, defaultSort: "maSP", rowsPerPage: 3);
}

<style type="text/css">
    .grid-footer {
        color: #000;
        font: 17px Calibri;
        text-align: center;
        font-weight: bold;
    }

        .grid-footer a {
            background-color: #ffffff;
            color: blue;
            box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
            padding: 1px 10px 2px 10px;
        }

            .grid-footer a:active, a:hover {
                background-color: #ffffff;
                color: #FFAD33;
                box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
            }

    .alternatingRowStyle {
        background-color: aliceblue;
    }

    table .table1 {
        text-align: left;
        margin-left: 0px;
        margin-right: 0px;
        width: 800px;
    }

    .tr, .td {
        text-align: center;
        padding-left: 40px;
    }

    #giohang {
        border-collapse: collapse;
        width: 100%;
    }

        #giohang tr {
        }

        #giohang td {
            border: 1px solid #000;
            padding: 8px;
            text-align: center;
            align-items: center;
        }

        #giohang img {
            width: 80px;
            height: 80px;
        }
        #giohang #tieude {
            background: black;
            color: white;
            font-weight: 700;
        }
    .submit {
        display: block;
        position: relative;
        padding: 11px 30px;
        letter-spacing: 1px;
        background: #212121;
        font-size: 1em;
        color: #fff;
        font-weight: 600;
        border: none;
        outline: none;
        transition: 0.5s all;
        text-transform: uppercase;
    }
</style>
<div class="container">

    <table align="center" border="1" id="giohang">
        <tr id="tieude">
            <td> Ảnh sản phẩm</td>

            <td> Mã sản phẩm </td>

            <td>Tên </td>

            <td>Số lượng</td>

            <td>Đơn giá</td>

            <td>Thành tiền</td>
            <td> Chỉnh sửa </td>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td><img src="@Url.Content("~/Image/San_pham/" + item.anhSP)" /></td>

                <td>@item.maSP</td>

                <td>@item.tenSP</td>
                @using (Html.BeginForm("CapNhatGioHang", "GioHang", new { @maSP = item.maSP })) 
                {
                <td>@Html.TextBox("textSL" , item.soLuong)</td>

                <td>@item.donGia</td>

                <td>@item.thanhTien</td>
                <td>           
                    <button class="submit" type="submit">sửa</button>
                    <br />
                    <br />
                    <button class="submit" onclick="location.href='@Url.Action("XoaGioHang", "GioHang",new { @maSP = item.maSP })';return false;">Xoá</button>

                </td>
                }
            </tr>
        }
    </table>
</div>

DAPTUGWEB/Views/GioHang/ThanhToan.cshtml
@model IEnumerable<DAPTUGWEB.Models.KHACHHANG>
@{
    ViewBag.Title = "ThanhToan";
    Layout = "~/Views/Layout/MainLayout.cshtml";
}


<link href="~/css/Checkout.css" rel="stylesheet" />

<div class="container">
    <div class="row checkout-left">
        <div class="col-md-7 checkout-left-basket">
            <h4>Đặt hàng thành công</h4>
            <ul>
                <li><i class="fa-solid fa-circle-check"></i></li>

                <li>
                    Mọi khiếu nại về sản phẩm, shop chỉ hổ trợ khi có video mở hàng từ lúc nguyên kiện
                    cho đến khi kết thúc (không cắt ghép chỉnh sửa clip), trường hợp sản phẩm trong đơn hàng này
                    không có video xác thực, mọi sự cố shop xin phép từ chối giải quyết
                </li>
                <li>Cảm ơn bạn đã mua hàng !   </li>

            </ul>
            
        </div>
        <div class="col-md-5 checkout-left-basket">
            <h4>Đơn hàng của bạn</h4>
            <ul>
                <li>Khách hàng  <span>@ViewBag.TenKH </span></li>
                <li>Số điện thoại  <span>@ViewBag.SDT </span></li>
                <li>Đia chỉ <span>@ViewBag.DiaChi</span></li>
                <li>Email <span>@ViewBag.Email</span></li>
                <li>Ngày đặt <span>@ViewBag.TgDat</span></li>
                <li>Tổng tiền <span>@ViewBag.TongTien.ToString("#,##0") VNĐ</span></li>
            </ul>
            <div class="d-flex my-4">
                <button class="submit mr-1" onclick="location.href='@Url.Action("GioHang", "GioHang")';return false;">Chi tiết đơn hàng</button>

                <button class="submit ml-auto" onclick="location.href='@Url.Action("Index", "Home")';return false;">Mua tiếp</button>
                
            </div>
        </div>
        <!--<div class="col-md-8 address_form">
        <h4>Thông tin giao hàng</h4>
        <form action="payment.html" method="post" class="creditly-card-form agileinfo_form">
            <section class="creditly-wrapper wrapper">
                <div class="information-wrapper">
                    <div class="first-row form-group">
                        <div class="controls">
                            <label class="control-label">Full name: </label>
                            <input class="billing-address-name form-control" type="text" name="name" placeholder="Full name">
                        </div>
                        <div class="card_number_grids">
                            <div class="card_number_grid_left">
                                <div class="controls">
                                    <label class="control-label">Mobile number:</label>
                                    <input class="form-control" type="text" placeholder="Mobile number">
                                </div>
                            </div>
                            <div class="card_number_grid_right">
                                <div class="controls">
                                    <label class="control-label">Landmark: </label>
                                    <input class="form-control" type="text" placeholder="Landmark">
                                </div>
                            </div>
                            <div class="clear"> </div>
                        </div>
                        <div class="controls">
                            <label class="control-label">Town/City: </label>
                            <input class="form-control" type="text" placeholder="Town/City">
                        </div>
                        <div class="controls">
                            <label class="control-label">Address type: </label>
                            <select class="form-control option-w3ls">
                                <option>Office</option>
                                <option>Home</option>
                                <option>Commercial</option>

                            </select>
                        </div>
                    </div>-->
        @*//<button class="submit">Giao hàng</button>*@

    </div>
</div>