DAPTUGWEB/Controllers/NhaCungCapController.cs
using DAPTUGWEB.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DAPTUGWEB.Controllers
{
    public class NhaCungCapController : Controller
    {
        ASP_QUAN_LY_SHOP_GIAY_6_6Entities db = new ASP_QUAN_LY_SHOP_GIAY_6_6Entities();
        // GET: SanPham
        public PartialViewResult NhaCungCapPartial()
        {
            var dsNhaCungCap = db.NHACCs.ToList();
            return PartialView(dsNhaCungCap);
        }
        public ViewResult SanPhamTheoNhaCungCap(string MANCC)
        {
            NHACC ncc = db.NHACCs.SingleOrDefault(n => n.MANCC == MANCC);
            if(ncc == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            List<SANPHAM> dssp = db.SANPHAMs.Where(n => n.MANCC == MANCC).ToList();
            if(dssp.Count() == 0)
            {
                ViewBag.SANPHAM= "Không tồn tại sản phầm của hãng "+ncc.TENNCC;
            }
            return View(dssp);

            
        }
    }
}

DAPTUGWEB/Views/NhaCungCap/NhaCungCapPartial.cshtml
@using DAPTUGWEB.Models;
@model List<NHACC>




@{ foreach (var item in Model)
    {
        <li class="level0">
            <a class='' href='@Url.Action("SanPhamTheoNhaCungCap", new { @MANCC = item.MANCC})'>
                
                <span>@item.TENNCC</span>
            </a>
        </li>
    }
}

DAPTUGWEB/Views/NhaCungCap/SanPhamTheoNhaCungCap.cshtml
@using DAPTUGWEB.Models;
@model List<SANPHAM>
@{
    ViewBag.Title = "SanPhamTheoNhaCungCap";
    Layout = "~/Views/Layout/MainLayout.cshtml";
}
<link href="~/css/index.css" rel="stylesheet" />

<link href="~/css/rightsidebar.css" rel="stylesheet" />

<link href="~/css/menuaccount.css" rel="stylesheet" />
<div class="container">

    <div class="container">
        <div class="row">
            <div class="col-lg-3 mb-3">

                <div id="mb_verticle_menu" class="menu-quick-select menu-account">

                    <div class="title_block">
                        <h3>Danh mục sản phẩm</h3>
                    </div>

                    <div id="menuverti" class="block_content navbar_menuvertical menu-account">
                        <ul class='nav_verticalmenu'>
                            @Html.Action("LoaiSanPhamPartial", "LoaiSanPham")
                        </ul>
                    </div>

                </div>
                <div id="mb_verticle_menu" class="menu-quick-select menu-account">

                    <div class="title_block">
                        <h3>Nhà cung cấp</h3>
                    </div>

                    <div id="menuverti" class="block_content navbar_menuvertical menu-account">
                        <ul class='nav_verticalmenu'>
                            @Html.Action("NhaCungCapPartial", "NhaCungCap")
                        </ul>
                    </div>

                </div>

            </div>

            <div class="col-lg-9">
                <div class="row">
                    <h2 style="color:blue; font-weight:300">@ViewBag.SANPHAM</h2>
                    @{ foreach (var item in Model)
                        {
                            <div class="product-grid1 col-md-4 ">
                               
                                <div class="product-pic">
                                    <a href="#"><img src="~/Image/San_pham/@item.ANHSP" title="product-name" /></a>
                                    <p>
                                        <span>@item.TENSP</span>
                                    </p>
                                </div>
                                <div class="product-info">

                                    <div class="product-info-cust">
                                        <a href="@Url.Action("../SanPham/ChiTietSanPham", new { @MASP = item.MASP})">Details</a>
                                    </div>
                                    <div class="product-info-price">
                                        <a href="details.html">@((float)item.DONGIA) Đ</a>
                                    </div>
                                    <div class="clear"> </div>
                                </div>
                                <div class="more-product-info">
                                    <span> </span>
                                </div>
                            </div>
                        }}
                </div>
            </div>
            <div class="clear"> </div>
        </div>
    </div>

    <div class="clear"> </div>
</div>