DAPTUGWEB/Controllers/QuanLyHoaDonController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DAPTUGWEB.Models;

namespace DAPTUGWEB.Controllers
{
    public class QuanLyHoaDonController : Controller
    {
        private ASP_QUAN_LY_SHOP_GIAY_6_6Entities db = new ASP_QUAN_LY_SHOP_GIAY_6_6Entities();

        // GET: QuanLyHoaDon
        public ActionResult Index()
        {
         
            return View(db.HOADONs.ToList());
        }

        // GET: QuanLyHoaDon/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HOADON hOADON = db.HOADONs.Find(id);
            
            if (hOADON == null)
            {
                return HttpNotFound();
            }
            return View(hOADON);
        }

        // GET: QuanLyHoaDon/Create
        public ActionResult Create()
        {
            ViewBag.MAKH = new SelectList(db.KHACHHANGs, "MAKH", "TENKH");
            
            ViewBag.IDTHANHTOAN = new SelectList(db.THANHTOANs, "IDTHANHTOAN", "HTTHANHTOAN");
            return View();
        }

        // POST: QuanLyHoaDon/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MAHD,MAKH,TGDAT,TGGIAO,IDTHANHTOAN,DATHANHTOAN,DAGIAO")] HOADON hOADON)
        {
            if (ModelState.IsValid)
            {
                db.HOADONs.Add(hOADON);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MAKH = new SelectList(db.KHACHHANGs, "MAKH", "TENKH", hOADON.MAKH);
            ViewBag.IDTHANHTOAN = new SelectList(db.THANHTOANs, "IDTHANHTOAN", "HTTHANHTOAN", hOADON.IDTHANHTOAN);
            return View(hOADON);
        }

        // GET: QuanLyHoaDon/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HOADON hOADON = db.HOADONs.Find(id);
            if (hOADON == null)
            {
                return HttpNotFound();
            }
            ViewBag.MAKH = new SelectList(db.KHACHHANGs, "MAKH", "TENKH", hOADON.MAKH);
           
            ViewBag.IDTHANHTOAN = new SelectList(db.THANHTOANs, "IDTHANHTOAN", "HTTHANHTOAN", hOADON.IDTHANHTOAN);
            return View(hOADON);
        }

       


        // POST: QuanLyHoaDon/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MAHD,MAKH,TGDAT,TGGIAO,IDTHANHTOAN,DATHANHTOAN,DAGIAO")] HOADON hOADON)
        {
            if (ModelState.IsValid)
            {
                db.Entry(hOADON).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MAKH = new SelectList(db.KHACHHANGs, "MAKH", "TENKH", hOADON.MAKH);
            
            ViewBag.IDTHANHTOAN = new SelectList(db.THANHTOANs, "IDTHANHTOAN", "HTTHANHTOAN", hOADON.IDTHANHTOAN);
            return View(hOADON);
        }

        // GET: QuanLyHoaDon/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HOADON hOADON = db.HOADONs.Find(id);
            if (hOADON == null)
            {
                return HttpNotFound();
            }
            return View(hOADON);
        }

        // POST: QuanLyHoaDon/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            HOADON hOADON = db.HOADONs.Find(id);
            db.HOADONs.Remove(hOADON);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DAPTUGWEB/Views/QuanLyHoaDon/Delete.cshtml
@model DAPTUGWEB.Models.HOADON

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Layout/MainLayout.cshtml";
    string tinhtrangdon = "";
    string thanhtoan = "";
}



<div class="container">
    <h4 style="color:red;"> Bạn có chắc chắn xóa đơn hàng này?</h4>
    <div class="row checkout-left">
        <div class="col-md-6 checkout-left-basket">
            <h4>Đơn hàng của bạn</h4>
            <ul>
                <li>Mã khách hàng  <span>@Html.DisplayFor(model => model.MAKH) </span></li>
                <li>Mã đơn hàng  <span>@Html.DisplayFor(model => model.MAHD) </span></li>
                <li>
                    Vận chuyển <span>
                        @{if (Model.DAGIAO == true)
                            { tinhtrangdon = "Đã giao"; }
                            else
                            { tinhtrangdon = "Chưa giao"; }
                        }
                        @tinhtrangdon
                    </span>
                </li>
                <li>Ngày đặt <span> @Html.DisplayFor(model => model.TGDAT)</span></li>
                <li>Ngày giao <span> @Html.DisplayFor(model => model.TGGIAO)</span></li>
                <li>
                    Thanh toán <span>
                        @{if (Model.DATHANHTOAN == true)
                            { thanhtoan = "Đã thanh toán"; }
                            else
                            { thanhtoan = "Chưa thanh toán"; }
                        }
                        @thanhtoan
                    </span>
                </li>
                <li>Hình thức thanh toán  <span>@Html.DisplayFor(model => model.THANHTOAN.HTTHANHTOAN) </span></li>
            </ul>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color d-flex my-4">
                    <input type="submit" value="Xoá" class="submit mr-4" />
                    <button class="submit" onclick="location.href='@Url.Action("Index", "QuanLyHoaDon")';return false;">Trở về</button>

                </div>
            }
        </div>
    </div>
</div>

DAPTUGWEB/Views/QuanLyHoaDon/Details.cshtml
@model DAPTUGWEB.Models.HOADON

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Layout/MainLayout.cshtml";
    string tinhtrangdon = "";
    string thanhtoan = "";
}
<link href="~/css/Checkout.css" rel="stylesheet" />

<div class="container">
    <div class="row checkout-left">

        <div class="col-md-6 checkout-left-basket">
            <h4>Chi tiết đơn hàng</h4>
            <ul>
                <li>Mã khách hàng  <span>@Html.DisplayFor(model => model.MAKH) </span></li>
                <li>Mã đơn hàng  <span>@Html.DisplayFor(model => model.MAHD) </span></li>
                <li>
                    Vận chuyển <span>
                        @{if (Model.DAGIAO == true)
                            { tinhtrangdon = "Đã giao"; }
                            else
                            { tinhtrangdon = "Chưa giao"; }
                        }
                        @tinhtrangdon
                    </span>
                </li>
                <li>Ngày đặt <span> @Html.DisplayFor(model => model.TGDAT)</span></li>
                <li>Ngày giao <span> @Html.DisplayFor(model => model.TGGIAO)</span></li>
                
                <li>
                    Thanh toán <span>
                        @{if (Model.DATHANHTOAN == true)
                            { thanhtoan = "Đã thanh toán"; }
                            else
                            { thanhtoan = "Chưa thanh toán"; }
                        }
                        @thanhtoan
                    </span>
                </li>
                <li>Hình thức thanh toán  <span>@Html.DisplayFor(model => model.THANHTOAN.HTTHANHTOAN) </span></li>
            </ul>
            <div class="d-flex my-4">
                <button class="submit mr-5" onclick="location.href='@Url.Action("Edit", "QuanLyHoaDon", new { id = Model.MAHD})';return false;">Cập nhật</button>

                <button class="submit ml-4" onclick="location.href='@Url.Action("Index", "QuanLyHoaDon")';return false;">Trở về</button>

            </div>
        </div>
    </div>
</div>

DAPTUGWEB/Views/QuanLyHoaDon/Edit.cshtml
@model DAPTUGWEB.Models.HOADON

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Layout/MainLayout.cshtml";
}



@using (Html.BeginForm("Edit", "QuanLyHoaDon", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*@Html.HiddenFor(model => model.MAHD)*@

        <div class="container">
            <div class="form-group">
                @Html.LabelFor(model => model.MAHD, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.MAHD, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                    @Html.ValidationMessageFor(model => model.MAHD, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.MAKH, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.MAKH, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                    @Html.ValidationMessageFor(model => model.MAKH, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TGDAT, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.TGDAT, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                    @Html.ValidationMessageFor(model => model.TGDAT, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TGGIAO, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.TGGIAO, new { htmlAttributes = new { @class = "form-control",    } })
                    @Html.ValidationMessageFor(model => model.TGGIAO, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.THANHTOAN, "Hình thức thanh toán", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    @Html.DropDownList("IDTHANHTOAN", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.IDTHANHTOAN, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-md-offset-2 col-md-2 ml-3">
                        <input type="submit" value="Cập nhật" class="submit" />
                    </div>
                    <div class="col-md-offset-2 col-md-5">
                        <button class="submit" onclick="location.href='@Url.Action("Index", "QuanLyHoaDon")';return false;">Trở về</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

}

DAPTUGWEB/Views/QuanLyHoaDon/Index.cshtml
@model IEnumerable<DAPTUGWEB.Models.HOADON>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Layout/QuanTriLayout.cshtml";
    var grid = new WebGrid(Model, canPage: true, defaultSort: "MAHD", rowsPerPage: 8);
    @Scripts.Render("~/Scripts/jquery-1.6.2.min.js")
}

<style type="text/css">
    .grid-footer {
        color: #000;
        font: 17px Calibri;
        text-align: center;
        font-weight: bold;
    }

        .grid-footer a {
            background-color: #ffffff;
            color: black;
            box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
            padding: 1px 10px 2px 10px;
        }

            .grid-footer a:active, a:hover {
                background-color: #ffffff;
                color: black;
                box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
                text-decoration: none;
                transition: linear 0.7s;
            }

    .alternatingRowStyle {
        background-color: aliceblue;
    }

    table .table1 {
        text-align: left;
        margin-left: 0px;
        margin-right: 0px;
        width: 800px;
    }

    .tr, .td {
        text-align: center;
    }

    .submit {
        display: block;
        position: relative;
        padding: 11px 30px;
        letter-spacing: 1px;
        background: #212121;
        font-size: 1em;
        color: #fff;
        font-weight: 600;
        border: none;
        outline: none;
        transition: 0.5s all;
        text-transform: uppercase;
    }
    
</style>

<div class="container">
    <div id="gridContent">
        @ViewBag.TB
        @grid.GetHtml(
         tableStyle: "table table-bordered table-hover",
         footerStyle: "grid-footer",
         fillEmptyRows: true,
         mode: WebGridPagerModes.Numeric,
         alternatingRowStyle: "alternatingRowStyle",
         columns: new[]  // colums in grid
         {
            grid.Column("STT",format: item => item.WebGrid.Rows.IndexOf(item) + 1 + Math.Round(Convert.ToDouble(grid.TotalRowCount / grid.PageCount) / grid.RowsPerPage) * grid.RowsPerPage * grid.PageIndex),
            grid.Column("MAHD","Mã hoá đơn"), //the model fields to display
            grid.Column("MAKH","Mã khách hàng"), //the model fields to display
            grid.Column("TGDAT","Ngày đặt hàng"),
            grid.Column("TGGIAO","Ngày giao hàng"),
            grid.Column("THANHTOAN.HTTHANHTOAN","Hình thức thanh toán"),
            grid.Column("Chức năng", format: @<text>
            <a href="@Url.Action("Edit",
                        new { id = item.MAHD})" class="edit-btn"><abbr title="Cập nhật dữ liệu"><img src="~/Image/edit.png" width="20" height="20" /></abbr></a>
            <a href="@Url.Action("Details",
                        new { id = item.MAHD})" class="edit-btn"><abbr title="Xem chi tiết"><img src="~/Image/details.png" width="20" height="20" /></abbr></a>
            <a href="@Url.Action("Delete",
                        new { id = item.MAHD})" class="edit-btn">
                <abbr title="Xóa dữ liệu">
                    <img src="~/Image/delete.png" width="20" height="20" />
                </abbr>
            </a>
                </text>),
            }
         )
    </div>
</div>