DAPTUGWEB/Controllers/LoaiSanPhamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DAPTUGWEB.Models;

namespace DAPTUGWEB.Controllers
{
    public class LoaiSanPhamController : Controller
    {
        // GET: LoaiSanPham

        ASP_QUAN_LY_SHOP_GIAY_6_6Entities db = new ASP_QUAN_LY_SHOP_GIAY_6_6Entities();
        public PartialViewResult LoaiSanPhamPartial()
        {
            var dsLoaiSP = db.LOAISPs.ToList();
            //var dsLoaiSP = db.LOAISPs.Take(3);
            return PartialView(dsLoaiSP);
        }
        public ViewResult SanPhamTheoLoai(string MALSP)
        {
            LOAISP lsp = db.LOAISPs.SingleOrDefault(n => n.MALSP == MALSP);
            if (lsp == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            List<SANPHAM> dssp = db.SANPHAMs.Where(n => n.MALSP == MALSP).ToList();
            if (dssp.Count() == 0)
            {
                ViewBag.SANPHAM = "Không tồn tại sản phầm của loại sản phẩm " + lsp.TENLSP;
            }
            return View(dssp);


        }
    }
}

DAPTUGWEB/Views/LoaiSanPham/LoaiSanPhamPartial.cshtml
@using DAPTUGWEB.Models;
@model List<LOAISP>



@{ foreach (var item in Model)
    {
        <li class="level0">
            <a class='' href='@Url.Action("SanPhamTheoLoai", new { @MALSP = item.MALSP})'>
               
                <span>@item.TENLSP</span>
            </a>
        </li>
    }
}

DAPTUGWEB/Views/LoaiSanPham/SanPhamTheoLoai.cshtml
@using DAPTUGWEB.Models;
@model List<SANPHAM>
@{
    ViewBag.Title = "SanPhamTheoLoai";
    Layout = "~/Views/Layout/MainLayout.cshtml";
}

<link href="~/css/rightsidebar.css" rel="stylesheet" />
<link href="~/css/index.css" rel="stylesheet" />
<link href="~/css/menuaccount.css" rel="stylesheet" />
<div class="container">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 mb-3">

                <div id="mb_verticle_menu" class="menu-quick-select menu-account">

                    <div class="title_block">
                        <h3>Danh mục sản phẩm</h3>
                    </div>
                    <div id="menuverti" class="block_content navbar_menuvertical menu-account">
                        <ul class='nav_verticalmenu'>
                            @Html.Action("LoaiSanPhamPartial", "LoaiSanPham")
                        </ul>
                    </div>
                </div>
                <div id="mb_verticle_menu" class="menu-quick-select menu-account">

                    <div class="title_block">
                        <h3>Nhà cung cấp</h3>
                    </div>

                    <div id="menuverti" class="block_content navbar_menuvertical menu-account">
                        <ul class='nav_verticalmenu'>
                            @Html.Action("NhaCungCapPartial", "NhaCungCap")
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-lg-9">
                <div class="row">
                    <h2 style="color:blue; font-weight:300">@ViewBag.SANPHAM</h2>
                    @{ foreach (var item in Model)
                        {
                            <div onclick="location.href='details.html';" class="product-grid1 col-md-4 ">
                                <div class="product-grid-head">
                                    <ul class="grid-social">
                                        <li><a class="facebook" href="#"><span> </span></a></li>
                                        <li><a class="twitter" href="#"><span> </span></a></li>
                                        <li><a class="googlep" href="#"><span> </span></a></li>
                                    </ul>
                                </div>
                                <div class="product-pic">
                                    <a href="#"><img src="~/Image/San_pham/@item.ANHSP" title="product-name" /></a>
                                    <p>

                                        <span>@item.TENSP</span>
                                    </p>
                                </div>
                                <div class="product-info">

                                    <div class="product-info-cust">
                                        <a href="@Url.Action("../SanPham/ChiTietSanPham", new { @MASP = item.MASP})">Details</a>
                                    </div>
                                    <div class="product-info-price">
                                        <a href="details.html">@((float)item.DONGIA) Đ</a>
                                    </div>
                                    <div class="clear"> </div>
                                </div>
                                <div class="more-product-info">
                                    <span> </span>
                                </div>
                            </div>
                        }}
                </div>
            </div>
            <div class="clear"> </div>
        </div>
    </div>
    <div class="clear"> </div>
</div>